name: ci
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        go: ["1.17.x"]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
      - name: "check generated code"
        run: |
          go generate ./...
          git diff --exit-code
      - name: "go vet"
        run: |
          go vet ./...
      - name: "go test"
        run: |
          go test -cover -coverprofile coverage.txt -race -v ./...
      - uses: codecov/codecov-action@v2
